name: yandex_mapkit_example
description: Demonstrates how to use the yandex_mapkit plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  permission_handler: ^10.4.0
  yandex_mapkit_lite:
    path: ../
  fluster: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
